### ISSUE TITLE
App should run offline

### ISSUE THREAD

**Issue by opensource21** [turtl/mobile#5]
I have many situations where I must edit and read y notes where I don't have an internet connection. So for me it's a must have requirement. Any chance to get such a feature?

**Comment by orthecreedence** [comment]
Well, right now the only reason Turtl needs to be connected is when you login or join (and a few other actions like sharing). If you log in, then turn off your wireless, you are in offline mode. You can add/edit/delete notes and boards as much as you want, and Turtl will sync those changes the next time you connect.

The real issue is that on Android, the app gets killed after being in the background for too long, which forces a logout (since we can't store your login info on disk).

The fix is, I think, to run a background service that holds your login info and sends it back into the app if it's killed so the app knows you're logged in and doesn't have to check with the server. This would mean as long as you're logged into Turtl, you'd have a full offline mode unless you manually log out of the app.

This issue is tracked here: https://trello.com/c/Bs4NPtgE and is at the top of my list of things to figure out.

**Comment by rubbingalcoholic** [comment]
Any background service should be optional, since a "stay logged in" feature
could make people vulnerable if their phone is stolen or compromised by
malware.

**Comment by orthecreedence** [comment]
Fair enough. This has been the #1 complaint of the android app users so far, so it will be on by default with on option to disable.

**Comment by opensource21** [comment]
Well even after a login you get a lot off messages that the sync fail after you have saved something.
Furhermore the https://trello.com/c/AycLbd4b is complete, but I can't find any commits for it. When will it be released?

**Comment by opensource21** [comment]
Why must I be online for login?

**Comment by orthecreedence** [comment]
You must be online because it was much simpler to architect the system that way, which meant I could release the mobile app and new desktop app much sooner. Setting up a local login system is tricky and hard to get right. It may make it into the app in the future but for now you have to have a connection to login.

Also, https://trello.com/c/AycLbd4b is complete and has been released since version 0.6.0. If you're getting errors while using Turtl in offline mode, that's a bug and I'd be very interested in trying to fix it. Can you provide more details about the messages you're receiving when in offline mode?

**Comment by 0f27** [comment]
It still required.

The issue is not only about app getting killed by android.

If I am in place without internet for several days and/or I have to reboot my device in zone without the internet connection avaliable there is no way to login the turtl app.

So offline login is necessary. It can be an optional feature which can be switched on/off in app by user. So for security purposes you can just switch it off but in general it is very useful to have app available offline.
